import {mkdir,cp,readFile,writeFile,rm} from 'node:fs/promises';
// Local preview: `npm run build` (indexing blocked, no signup endpoint).
// Deploy build for polyphonic.chat/beta:
//   BASE_PATH=/beta/ PUBLISH=1 SIGNUP_ENDPOINT=https://... PRIVACY_URL=https://polyphonic.chat/privacy npm run build
const base=process.env.BASE_PATH||'/';
const publish=process.env.PUBLISH==='1';
const siteUrl=process.env.SITE_URL||(publish?'https://polyphonic.chat/beta/':'');
if(!base.startsWith('/')||!base.endsWith('/'))throw new Error('BASE_PATH must start and end with /');
await rm('dist',{recursive:true,force:true});
await mkdir('dist',{recursive:true});
await cp('assets','dist/assets',{recursive:true});
// Exploratory studies and unused brand variants stay out of the deployable bundle.
for(const f of ['brand/agents','brand/agents.html','brand/study.html','brand/README.md','brand/polyphonic-display.svg','brand/polyphonic-matrix.svg','brand/polyphonic-soft.svg','brand/polyphonic-sharp.svg'])await rm(`dist/assets/${f}`,{recursive:true,force:true});
let html=await readFile('index.html','utf8');
if(html.includes('{{')||html.includes('x-dc'))throw new Error('Editor template remains in output');
if(publish){
  const before=html;
  html=html.replace('<meta name="robots" content="noindex, nofollow">','');
  if(html===before)throw new Error('Expected preview robots meta tag not found');
}
const rewrite=text=>text.replace(/(["'(=]|&quot;)assets\//g,`$1${base}assets/`);
if(base!=='/'){
  html=rewrite(html);
  for(const file of ['dist/assets/demo.js']){await writeFile(file,rewrite(await readFile(file,'utf8')));}
}
await writeFile('dist/index.html',html);
const config={signupEndpoint:process.env.SIGNUP_ENDPOINT||'',privacyUrl:process.env.PRIVACY_URL||'',siteUrl};
await writeFile('dist/assets/config.js',`// Generated by scripts/build.mjs. No visitor data is sent unless signupEndpoint is set.\nwindow.POLYPHONIC_CONFIG = Object.freeze(${JSON.stringify(config)});\n`);
if(base==='/')await writeFile('dist/robots.txt',publish?'User-agent: *\nAllow: /\n':'User-agent: *\nDisallow: /\n');
console.log(`Built dist/ (base ${base}, ${publish?'publishable':'preview: indexing disabled'}, signup ${config.signupEndpoint?'configured':'not configured'}).`);
