import {chromium,webkit,firefox} from 'playwright';
import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),axeSource=await fs.readFile(require.resolve('axe-core/axe.min.js'),'utf8');
const report={checks:[],errors:[],axe:[],browsers:{}};
const b=await chromium.launch();const context=await b.newContext({viewport:{width:1440,height:1000}});const p=await context.newPage();p.on('pageerror',e=>report.errors.push(e.message));
await p.goto('http://127.0.0.1:8744/',{waitUntil:'networkidle'});const app=p.locator('.demo-app');
await p.screenshot({animations:'disabled',path:'audit/explorer-hero.png'});await app.scrollIntoViewIfNeeded();await p.screenshot({animations:'disabled',path:'audit/explorer-app.png'});
const scan=async name=>{await p.evaluate(axeSource);const v=await p.evaluate(async()=>{const r=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return r.violations.map(x=>({id:x.id,nodes:x.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))});report.axe.push({name,violations:v});};
await scan('initial');
for(const view of ['Library','New conversation','Agents','Activity','Brain','Settings','Luca','Mira','Luca & Mira','Claude Code','Codex','Kimi Code','Grok','Hermes','OpenClaw']){await app.locator(`.d-nav [data-view="${view}"]`).click();assert.equal(await app.locator('.d-title strong').innerText(),view);}
report.checks.push('Every sidebar section, conversation, and six runtime views opens');
await app.locator('.d-nav [data-view="Settings"]').click();await app.locator('select').selectOption('Codex');assert.match(await app.locator('.d-settings-row').nth(2).innerText(),/identity remains/);report.checks.push('Runtime switches while identity and context remain');
/* WP-03: the demo's Brain is now the app's Connections screen. The four Northstar grants live outside the frame (verify.mjs still covers them); in the frame we exercise the connect action from the keyboard. */
await app.locator('.d-nav [data-view="Brain"]').click();const connect=app.getByRole('button',{name:'Connect repositories',exact:true});await connect.focus();await p.keyboard.press('Enter');assert.match(await app.locator('.d-live-note').innerText(),/3 repositories connected/);await p.screenshot({animations:'disabled',path:'audit/explorer-brain.png'});await scan('brain');
/* WP-03: the source rows left Brain with the grants; Library still opens them. */
await app.locator('.d-nav [data-view="Library"]').click();await app.getByRole('button',{name:'Open Northstar brief.md',exact:true}).click();assert.match(await app.locator('.d-drawer-body').innerText(),/One route/);await app.getByRole('button',{name:'Close drawer',exact:true}).click();
await app.locator('.d-nav [data-view="Luca"]').click();await app.getByRole('button',{name:'Toggle conversation drawer',exact:true}).click();await p.screenshot({animations:'disabled',path:'audit/explorer-drawer.png'});await scan('drawer');await app.getByRole('button',{name:'Close drawer',exact:true}).click();
await app.getByRole('button',{name:'Toggle split view',exact:true}).click();assert.ok(await app.locator('.d-secondary').isVisible());await p.screenshot({animations:'disabled',path:'audit/explorer-split.png'});await app.getByRole('button',{name:'Close split view',exact:true}).click();
await app.locator('#demo-message').fill('Could Claude Code and Kimi work on design while Codex handles architecture?');await app.getByRole('button',{name:'Send demo message',exact:true}).click();assert.match(await app.locator('.d-transcript').innerText(),/opened a shared design conversation/);report.checks.push('Typed collaboration request creates a shared-work reply');
await app.getByRole('button',{name:'Pop out chat',exact:true}).click();const pop=p.getByRole('dialog',{name:'Detached Luca chat',exact:true});assert.ok(await pop.isVisible());await p.screenshot({animations:'disabled',path:'audit/explorer-popout.png'});await scan('popout');await pop.getByRole('textbox').fill('What context do you remember?');await pop.getByRole('button',{name:'Send demo message'}).click();assert.match(await pop.locator('.d-transcript').innerText(),/You prefer small releases/);
const winPromise=context.waitForEvent('page');await pop.getByRole('button',{name:'Open chat in a separate window'}).click();const child=await winPromise;await child.waitForLoadState('networkidle');assert.equal(await child.title(),'Luca — Polyphonic demo');await child.getByRole('textbox').fill('Give me an update');await child.getByRole('button',{name:'Send demo message',exact:true}).click();await p.waitForTimeout(300);assert.match(await app.locator('.d-transcript').innerText(),/Give me an update/);await child.close();report.checks.push('Detached dialog and separate browser window both send; parent receives shared history');
await app.getByRole('button',{name:'Expand app demo',exact:true}).click();assert.ok(await p.getByRole('dialog',{name:'Expanded Polyphonic app demo'}).isVisible());await p.keyboard.press('Escape');assert.equal(await app.getAttribute('aria-modal'),null);report.checks.push('Expanded app closes with Escape and restores focus');
await app.getByRole('button',{name:'Search the demo',exact:true}).click();await app.locator('#demo-search').fill('brief');assert.equal(await app.locator('.d-search-result').count(),1);await app.locator('.d-search-result').click();assert.match(await app.locator('.d-drawer-body').innerText(),/first release/);report.checks.push('Search filters sources and opens the matching document');await app.getByRole('button',{name:'Close drawer',exact:true}).click();
await p.getByRole('button',{name:'Play guided tour',exact:true}).click();assert.match(await p.locator('#replay-demo').innerText(),/Stop tour/);await p.locator('#replay-demo').click();report.checks.push('Guided tour starts and stops');
await p.getByRole('button',{name:'Pause page animation',exact:true}).click();const progress=await p.evaluate(()=>PolyphonicDemo.state.progress);await p.waitForTimeout(2000);assert.equal(await p.evaluate(()=>PolyphonicDemo.state.progress),progress);await p.emulateMedia({reducedMotion:'reduce'});report.checks.push('Global pause and reduced motion preserve a usable static demo');
for(const width of [390,320]){await p.setViewportSize({width,height:844});await p.evaluate(()=>PolyphonicDemo.navigate('Luca'));await app.scrollIntoViewIfNeeded();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);await p.screenshot({animations:'disabled',path:`audit/explorer-${width}.png`});await app.getByRole('button',{name:'Toggle app navigation',exact:true}).click();await app.locator('.d-nav [data-view="Brain"]').click();assert.ok(await app.getByRole('heading',{name:'Brain',exact:true}).isVisible());/* WP-03: Brain's heading is the app's own */await app.getByRole('button',{name:'Toggle conversation drawer',exact:true}).click();await p.screenshot({animations:'disabled',path:`audit/explorer-${width}-drawer.png`});await app.getByRole('button',{name:'Close drawer',exact:true}).click();}
await p.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await scan('mobile');await b.close();
for(const [name,engine] of [['webkit',webkit],['firefox',firefox]]){const browser=await engine.launch();const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});await page.goto('http://127.0.0.1:8744/',{waitUntil:'networkidle'});await page.locator('.demo-app').scrollIntoViewIfNeeded();await page.getByRole('button',{name:'Toggle app navigation',exact:true}).click();await page.locator('.d-nav [data-view="Agents"]').click();assert.equal(await page.locator('.d-agent-card').count(),7);/* WP-03: Agents lists seven personal agents, not six runtime cards */await page.getByRole('button',{name:'Pop out chat',exact:true}).click();assert.ok(await page.getByRole('dialog',{name:'Detached Luca chat'}).isVisible());await page.keyboard.press('Escape');report.browsers[name]={navigation:true,popout:true,overflow:await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)};await browser.close();}
await fs.writeFile('audit/explorer-verification.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
