import {chromium,webkit,firefox} from 'playwright';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const out={checks:[],browsers:{},errors:[],contrast:[]};
const b=await chromium.launch();const page=await b.newPage({viewport:{width:1440,height:1000}});
page.on('pageerror',e=>out.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')out.errors.push(m.text())});
await page.goto('http://127.0.0.1:8744/',{waitUntil:'networkidle'});
await page.emulateMedia({reducedMotion:'reduce'});
for(const btn of await page.locator('.grant-toggle[data-agent="luca"]').all())if(await btn.getAttribute('aria-checked')==='true')await btn.click();assert.match(await page.locator('#luca-knows').innerText(),/don’t have context/);await page.getByRole('checkbox',{name:'Luca can see Northstar brief.md',exact:true}).focus();await page.keyboard.press('Space');assert.match(await page.locator('#luca-knows').innerText(),/one route/);out.checks.push('Brain grant state and response; Space key toggles');
await page.getByRole('button',{name:'Deny',exact:true}).click();assert.match(await page.locator('#permission-result').innerText(),/Nothing changes/);assert.equal(await page.locator('#reset-permission').evaluate(e=>e===document.activeElement),true);await page.getByRole('button',{name:'Try again',exact:true}).click();await page.getByRole('button',{name:'Allow once',exact:true}).click();assert.match(await page.locator('#permission-result').innerText(),/Allowed once/);out.checks.push('Permission deny / allow / reset and focus return');
await page.getByRole('button',{name:'Request the beta',exact:true}).click();assert.equal(await page.locator('#email').getAttribute('aria-invalid'),'true');await page.locator('#email').fill('riley-audit@example.test');await page.getByRole('button',{name:'Request the beta',exact:true}).click();assert.match(await page.locator('#signup-note').innerText(),/has not been sent or saved/);out.checks.push('Required email error and honest unconfigured state');
await page.evaluate(await fs.readFile(require.resolve('axe-core/axe.min.js'),'utf8'));
out.axe=await page.evaluate(async()=>{const r=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return r.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))});
for(const width of [1440,1024,768,390,320]){await page.setViewportSize({width,height:900});const geometry=await page.evaluate(()=>({w:innerWidth,scroll:document.documentElement.scrollWidth,small:[...document.querySelectorAll('button,a,input')].filter(e=>e.getBoundingClientRect().width&&e.getBoundingClientRect().height<24).map(e=>e.textContent)}));assert.equal(geometry.scroll,width);out.checks.push(`${width}px document: no overflow`);out.browsers[`chromium-${width}`]=geometry;}
await page.setViewportSize({width:720,height:500});out.reflow720=await page.evaluate(()=>({w:innerWidth,scroll:document.documentElement.scrollWidth}));
await page.setViewportSize({width:390,height:844});await page.locator('#beta').scrollIntoViewIfNeeded();await page.screenshot({path:'audit/final-mobile-beta.png'});await page.locator('#control').scrollIntoViewIfNeeded();await page.screenshot({path:'audit/final-mobile-control.png'});
await page.evaluate(()=>window.scrollTo(0,0));await page.keyboard.press('Control+Home');await page.reload();await page.keyboard.press('Tab');out.firstFocus=await page.evaluate(()=>document.activeElement.textContent);assert.equal(out.firstFocus,'Skip to content');out.checks.push('Skip link first in keyboard order');
const mock=await b.newPage();await mock.route('**/assets/config.js',r=>r.fulfill({contentType:'text/javascript',body:"window.POLYPHONIC_CONFIG={signupEndpoint:'/api/beta'}"}));let requests=0;
await mock.route('**/api/beta',async r=>{requests++;await new Promise(res=>setTimeout(res,200));await r.fulfill({status:200,contentType:'application/json',body:'{}'})});
await mock.goto('http://127.0.0.1:8744/');await mock.locator('#email').fill('test@example.test');await mock.locator('#signup-submit').click();await mock.waitForTimeout(400);assert.match(await mock.locator('#signup-note').innerText(),/on the list/);assert.equal(requests,1);out.checks.push('Configured signup success, single submission (mocked locally, no account contacted)');
await mock.unroute('**/api/beta');await mock.route('**/api/beta',r=>r.fulfill({status:503,body:'unavailable'}));await mock.reload();await mock.locator('#email').fill('test@example.test');await mock.locator('#signup-submit').click();await mock.waitForTimeout(200);assert.match(await mock.locator('#signup-note').innerText(),/couldn’t be confirmed/);out.checks.push('Signup service failure / retry state (local mock)');
const nojs=await b.newPage({javaScriptEnabled:false,viewport:{width:390,height:844}});await nojs.goto('http://127.0.0.1:8744/');assert.equal(await nojs.locator('h1').innerText(),'Your agents,\ntogether.');assert.ok((await nojs.locator('.chat-transcript').innerText()).includes('Codex finished'));out.checks.push('Static hero and complete conversation readable without JavaScript');await b.close();
for(const [name,engine] of [['webkit',webkit],['firefox',firefox]]){try{const browser=await engine.launch();const p=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});await p.goto('http://127.0.0.1:8744/',{waitUntil:'networkidle'});out.browsers[name]=await p.evaluate(()=>({w:innerWidth,scroll:document.documentElement.scrollWidth,title:document.title}));await p.screenshot({path:`audit/final-${name}-mobile.png`});await browser.close()}catch(e){out.browsers[name]={unavailable:e.message.slice(0,180)}}}
await fs.writeFile('audit/verification.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));
